version: "3.2"

services:
  pg:
    image: postgis/postgis:11-3.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kata
    ports:
      - 5432:5432
    volumes:
      - ./backup/:/mnt/backups/
